[package]
name = "jlox"
version = "0.1.0"
authors = ["franek <franeklubi@gmail.com>"]
edition = "2018"

[dependencies]
exitcode = "1.1.2"
termcolor = "1.1.2"

[profile.release]
lto = "fat"
opt-level = 3
panic = "abort"
