binop_separator = "Front"
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
max_width = 80
hard_tabs = true
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_comments = true
condense_wildcard_suffixes = true
format_strings = true
